### ISSUE TITLE
Please update them?

### ISSUE THREAD

**Issue by billy-mosse** [Antigrapist/Mother_of_Learning#2]
Hey! Thanks for the ebooks. Could you please update them? :-)

**Comment by AgentFire** [comment]
What's there to update?

**Comment by Ahmed-Halat-iseehear** [comment]
104-106 have been posted! The book is finished, now we wait for the epilogue and it’s done forever.

**Comment by AlexRaubach** [comment]
There was nothing to update until yesterday but the ebook versions are now up to date.
